### ISSUE TITLE
屎山是怎么形成的

### ISSUE THREAD

**Issue by Sevenyine** [Todysheep/nonebot_plugin_bottle#61]
想写一个 获取用户回复的消息 扔漂流瓶的插件 但屎山就这样形成了

目前写的在这 https://github.com/Sevenyine/nonebot_plugin_bottle/commit/9740e33f4ddd0b0f6b6ac6a4aeaba4794b27f522

本来前面args的值我也模仿着正常流程写好了 结果直接报错 是在图片处理的地方

在init.py里 args 的样子已经和普通扔瓶子一样了

这是回复扔瓶的args（爆错）

`[CQ:image,file=1a9f170d8c84197df0a46ec02a758321.image,subType=0,url=https://gchat.qpic.cn/gchatpic_new/1/0-0-1A9F170D8C84197DF0A46EC02A758321/0?term=2]
`
这是成功扔瓶的args（用消息嵌套图片的方式）

`[CQ:image,file=ff7af77814bdb9b6fa47b54c01c77b5f.image,subType=0,url=https://gchat.qpic.cn/gchatpic_new/3190495308/814037586-3155443062-FF7AF77814BDB9B6FA47B54C01C77B5F/0?term=2&amp;is_origin=0]
`
Cinte佬有什么思路吗 啊啊啊我真是要被自己写的屎搞疯了

主要是回复后用bot.get_msg(message_id=reply_id)获取的消息，type不是Message，不能直接等价替换

<img width="286" alt="image" src="https://github.com/Todysheep/nonebot_plugin_bottle/assets/65720409/845da36e-8279-4019-8793-9babb8368707">

<img width="419" alt="image" src="https://github.com/Todysheep/nonebot_plugin_bottle/assets/65720409/66a4fa7d-b578-43f6-a80d-42279e838fc2">

```
12-08 22:53:51 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bottle, lineno=70) running complete
12-08 22:53:51 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bottle, lineno=70) failed.
Traceback (most recent call last):
  File "/root/GZbot2/bot.py", line 38, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 201, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 821, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_bottle/__init__.py", line 210, in _
    content=await serialize_message(message=args),
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_bottle/data_source.py", line 64, in serialize_message
    await cache_file(message)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_bottle/data_source.py", line 37, in cache_file
    *[cache_image_url(seg, client) for seg in msg if seg.type == "image"]
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_bottle/data_source.py", line 37, in <listcomp>
    *[cache_image_url(seg, client) for seg in msg if seg.type == "image"]
AttributeError: 'str' object has no attribute 'type'
```

**Comment by LambdaYH** [comment]
https://github.com/Todysheep/nonebot_plugin_bottle/commit/45084ed5827ed540dd87e8f264e626774bddf44e

直接`Message(str)`就能把字符串类型转换的其实

**Comment by Sevenyine** [comment]
草 原来是这么实现的吗 Orz
真的感谢了(⁎⁍̴̛ᴗ⁍̴̛⁎)我还是安心搬砖吧
