### ISSUE TITLE
貌似GIF不行？

### ISSUE THREAD

**Issue by yokoyamamio** [Todysheep/nonebot_plugin_bottle#70]
```
05-11 18:09:01 [INFO] nonebot | Event will be handled by Matcher(type='message', module=dicergirl, lineno=107)
05-11 18:09:01 [INFO] nonebot | Matcher(type='message', module=dicergirl, lineno=107) running complete
05-11 18:09:01 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bottle, lineno=87)
05-11 18:09:02 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bottle, lineno=87) running complete
05-11 18:09:02 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bottle, lineno=87) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/QBOT/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/root/QBOT/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot_plugin_bottle/__init__.py", line 322, in _
    await get.send(MessageSegment.reply(message_id) + bottle_message)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 566, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 228, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 181, in send
    return await bot.send_msg(**params)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 122, in call_api
    raise exception
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='Error: Empty file\n    at readFileAsync (/root/qqbot/qqbot/napcat.cjs:4293:20)', wording='Error: Empty file\n    at readFileAsync (/root/qqbot/qqbot/napcat.cjs:4293:20)', echo='4')
```

**Comment by yokoyamamio** [comment]
![image](https://github.com/Todysheep/nonebot_plugin_bottle/assets/91837578/cc1707bb-192a-48a3-b1c7-8e0492040f79)
qinkgkan请看PNG

**Comment by Icexbb** [comment]
这个不是gif的原因 see #71
