### ISSUE TITLE
无法加载插件，版本为2.1.0.0，未开启webui

### ISSUE THREAD

**Issue by luoye520ww** [Todysheep/nonebot_plugin_bottle#83]
12-08 16:45:56 [ERROR] nonebot | Failed to import "nonebot_plugin_bottle"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Users\Administrator\Desktop\nb\mai\.venv\Lib\site-packages\nonebot\plugin\load.py", line 133, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\nb\mai\.venv\Lib\site-packages\nonebot\plugin\load.py", line 67, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\nb\mai\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 205, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\nb\mai\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\nb\mai\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 169, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\Administrator\Desktop\nb\mai\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 257, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\nb\mai\.venv\Lib\site-packages\nonebot_plugin_bottle\__init__.py", line 48, in <module>
    from . import webui
  File "C:\Users\Administrator\Desktop\nb\mai\.venv\Lib\site-packages\nonebot_plugin_bottle\webui\__init__.py", line 3, in <module>
    from .api import router
  File "C:\Users\Administrator\Desktop\nb\mai\.venv\Lib\site-packages\nonebot_plugin_bottle\webui\api.py", line 2, in <module>
    from .utils import generate_password
ModuleNotFoundError: No module named 'nonebot_plugin_bottle.webui.utils

**Comment by LambdaYH** [comment]
试试2.1.0.1（少传了一个文件
