### ISSUE TITLE
迁移漂流瓶

### ISSUE THREAD

**Issue by luoye520ww** [Todysheep/nonebot_plugin_bottle#85]
这么晚打扰佬不好意思，想问一下怎么把另外一台服务器现有的漂流瓶迁移到本地电脑另外一个项目的漂流瓶（目前为空的），直接复制在cache文件夹后在2.1.0.2版本无法识别漂流瓶，2个插件版本都是2.1.0.2

**Comment by LambdaYH** [comment]
cache下存的应该是图片缓存。
漂流瓶数据库使用的是[nonebot-plugin-datastore](https://github.com/he0119/nonebot-plugin-datastore)
如果什么配置都没改过的话，那默认路径就是配置项`datastore_database_url`的默认值

**Comment by luoye520ww** [comment]
![image](https://github.com/user-attachments/assets/02c706e0-2f9b-445d-a15f-998954ee46a7)
有漂流瓶存在但还是显示错误了，可以请佬帮我看看嘛，麻烦了。
--------
12-10 21:07:09 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bottle, lineno=91) running complete
12-10 21:07:09 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bottle, lineno=91) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
    nonebot.run()
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 188, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 678, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2033, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    return await coro
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\nonebot\message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 837, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\nonebot_plugin_bottle\__init__.py", line 344, in _
    bottle_content = (await deserialize_message(bottle.content)).extract_plain_text().strip()
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\nonebot_plugin_bottle\data_source.py", line 84, in deserialize_message
    seg["data"]["file"] = await file_to_b64(cache_dir / seg["data"]["file"])
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\nonebot_plugin_bottle\data_source.py", line 68, in file_to_b64
    async with aiofiles.open(file, 'rb') as f:
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\aiofiles\base.py", line 98, in __aenter__
    self._obj = await self._coro
  File "C:\Users\Administrator\Desktop\maimai\.venv\Lib\site-packages\aiofiles\threadpool\__init__.py", line 94, in _open
    f = yield from loop.run_in_executor(executor, cb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'data\\bottle\\cache\\f42f5ba07481acf50584cc6e9d9ad5b8.cache'

**Comment by LambdaYH** [comment]
这看着是历史的缓存文件不在路径下了，以前的都迁移了吗？。我改一下让没找到的文件就不展示吧

**Comment by luoye520ww** [comment]
好的谢谢佬，以前服务器的都全部迁移了新漂流瓶了

**Comment by LambdaYH** [comment]
试试v2.1.0.4，如果找不到缓存的图片的话就会显示成`[图片]`

**Comment by luoye520ww** [comment]
好的佬，已经完美解决了
